name: frontend
description: A Flutter RideLog application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State management
  provider: ^6.0.5
  
  # HTTP requests
  http: ^1.1.0
  
  # For icons
  cupertino_icons: ^1.0.2
  intl: ^0.20.2

  # Charts
  fl_chart: ^0.68.0

  # Local session storage
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
